import { test, expect } from '@playwright/test';
import { PDFDocument, degrees } from 'pdf-lib';

test('upload, place, save, reopen, sign, download and reuse a template', async ({ page }) => {
    const errors = [];
    const templateName = `Browser template ${Date.now()}`;
    page.on('pageerror', error => errors.push(error.message));
    await page.goto('/login');
    await page.getByLabel('Username or email', { exact: true }).fill('browser@example.test');
    await page.getByLabel('Password', { exact: true }).fill('browser-test-password');
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    await expect(page).toHaveURL(/dashboard/);
    await page.getByRole('link', { name: 'Signatures', exact: true }).click();
    await page.getByLabel('Signature name').fill('Browser signature');
    const png = await page.evaluate(() => {
        const canvas = document.createElement('canvas'); canvas.width = 240; canvas.height = 80;
        const ctx = canvas.getContext('2d'); ctx.font = 'italic 36px serif'; ctx.fillText('Test Signer', 10, 50);
        return canvas.toDataURL('image/png').split(',')[1];
    });
    await page.getByLabel('Signature image').setInputFiles({ name: 'signature.png', mimeType: 'image/png', buffer: Buffer.from(png, 'base64') });
    await page.getByRole('button', { name: 'Save signature', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Browser signature' }).first()).toBeVisible();
    const pdf = await PDFDocument.create(); pdf.addPage([612, 792]); const rotated = pdf.addPage([612, 792]); rotated.setRotation(degrees(90));
    await page.goto('/documents/create');
    await page.getByLabel('PDF file').setInputFiles({ name: 'browser-contract.pdf', mimeType: 'application/pdf', buffer: Buffer.from(await pdf.save()) });
    await page.getByRole('button', { name: 'Upload and open editor' }).click();
    await expect(page).toHaveURL(/documents\/\d+\/edit/);
    const editorUrl = page.url();
    await page.getByRole('button', { name: /Browser signature/ }).first().click();
    const overlay = page.getByRole('button', { name: 'Select signature', exact: true });
    await expect(overlay).toBeVisible();
    const bounds = await overlay.boundingBox();
    await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
    await page.mouse.down(); await page.mouse.move(bounds.x + bounds.width / 2 + 80, bounds.y + bounds.height / 2 + 100, { steps: 8 }); await page.mouse.up();
    const moved = await overlay.boundingBox();
    expect(moved.x).toBeGreaterThan(bounds.x + 60);
    await page.mouse.move(moved.x + moved.width - 1, moved.y + moved.height - 1);
    await page.mouse.down(); await page.mouse.move(moved.x + moved.width + 40, moved.y + moved.height + 14, { steps: 8 }); await page.mouse.up();
    expect((await overlay.boundingBox()).width).toBeGreaterThan(moved.width + 20);
    await page.getByRole('button', { name: 'Save draft', exact: true }).click();
    await expect(page.getByText('All changes saved')).toBeVisible();
    await page.reload(); await expect(overlay).toBeVisible();
    await page.getByRole('button', { name: 'Next', exact: true }).click();
    await page.getByRole('button', { name: 'Name', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Select name', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Undo', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Select name', exact: true })).toHaveCount(0);
    await page.getByRole('button', { name: 'Redo', exact: true }).click();
    await page.getByLabel('Save current layout as').fill(templateName);
    await page.getByRole('button', { name: 'Save template', exact: true }).click();
    await expect(page.getByText('Template saved.', { exact: false })).toBeVisible();
    await page.getByRole('button', { name: 'Preview signed PDF' }).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Save signed copy and download' }).click();
    const download = await downloadPromise;
    expect(download.suggestedFilename()).toBe('browser-contract-signed.pdf');
    await expect(page.getByText('All changes saved')).toBeVisible();
    await page.goto(editorUrl);
    await page.getByLabel('Saved template').selectOption({ label: templateName });
    page.once('dialog', dialog => dialog.accept());
    await page.getByRole('button', { name: 'Apply template', exact: true }).click();
    await expect(overlay).toBeVisible();
    await expect(page.getByRole('button', { name: 'Name', exact: true })).toBeEnabled();
    await page.getByRole('button', { name: 'Save draft', exact: true }).click();
    await expect(page.getByText('All changes saved')).toBeVisible();
    await page.screenshot({ path: 'test-results/editor.png', fullPage: true });
    expect(errors).toEqual([]);
});
