<?php

use App\Http\Controllers\ActivityController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\SignatureController;
use App\Http\Controllers\SignedDocumentController;
use App\Http\Controllers\TemplateController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Generated by DevKit when this project was created. Add your own routes
| below — the ones above are only the entry points the starter shell needs.
|
*/

Route::redirect('/', '/dashboard')->name('home');
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'create'])->name('login');
    Route::post('/login', [AuthController::class, 'store'])->middleware('throttle:20,1');
});
Route::middleware('auth')->group(function () {
    Route::post('/logout', [AuthController::class, 'destroy'])->name('logout');
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::resource('documents', DocumentController::class)->except('update');
    Route::get('/documents/{document}/file', [DocumentController::class, 'file'])->name('documents.file');
    Route::get('/documents/{document}/download', [DocumentController::class, 'download'])->name('documents.download');
    Route::put('/documents/{document}/placements', [SignedDocumentController::class, 'draft'])->name('documents.placements');
    Route::post('/documents/{document}/sign', [SignedDocumentController::class, 'store'])->middleware('throttle:10,1')->name('documents.sign');
    Route::resource('signatures', SignatureController::class)->only('index', 'store', 'destroy');
    Route::get('/signatures/{signature}/image', [SignatureController::class, 'image'])->name('signatures.image');
    Route::patch('/signatures/{signature}/default', [SignatureController::class, 'makeDefault'])->name('signatures.default');
    Route::resource('templates', TemplateController::class)->only('index', 'store', 'update', 'destroy');
    Route::get('/activity', ActivityController::class)->name('activity');
});
